### ISSUE TITLE
DATEADD in Databricks/Spark failing 

### ISSUE THREAD

**Issue by kzollove** [OHDSI/SqlRender#376]
Please let me know if I should add any detail. Feel free to close if this outside the package's expected coverage. Thanks for your work to maintain this project!

In databricks SQL I am able to:
```sql
CREATE OR REPLACE TABLE my_catalog.my_schema.test_dateadd (num_year_to_add int);
INSERT INTO my_catalog.my_schema.test_dateadd (num_year_to_add) VALUES (1),(2),(3);
SELECT 
DATEADD(YEAR, num_year_to_add,TIMESTAMP('2023-01-01')) AS added_date
FROM my_catalog.my_schema.test_dateadd
```
And it outputs:
|added_date|
|------|
|2024-01-01|
|2025-01-01|
|2026-01-01|

In SqlRender it fails:
```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, num_year_to_add,TIMESTAMP('2023-01-01')) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

It seems to be converting it to more "general" SQL that itself fails in Databricks:
```
[PARSE_SYNTAX_ERROR] Syntax error at or near 'year'. SQLSTATE: 42601 (line 2, pos 53)

== SQL ==
SELECT 
 (TIMESTAMP('2023-01-01') + INTERVAL num_year_to_add year) AS added_date
-----------------------------------------------------^^^
 FROM my_catalog.my_schema.test_dateadd
```

I will note that this works in SqlRender:
```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, 1,TIMESTAMP('2023-01-01')) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

<details>

<summary>Here is the whole error:</summary>

Error in `.createErrorReport()`:
! Error executing SQL:
java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [PARSE_SYNTAX_ERROR] org.apache.spark.sql.catalyst.parser.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'year'. SQLSTATE: 42601 (line 2, pos 53)

== SQL ==
SELECT 
 (TIMESTAMP('2023-01-01') + INTERVAL num_year_to_add year) AS added_date
-----------------------------------------------------^^^
 FROM my_catalog.my_schema.test_dateadd

	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:49)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$execute$1(SparkExecuteStatementOperation.scala:756)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:45)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:595)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$5(SparkExecuteStatementOperation.scala:420)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.SQLExecution$.withRootExecution(SQLExecution.scala:704)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:420)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:48)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:253)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:249)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:46)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:43)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:27)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags(AttributionContextTracing.scala:95)
	at com.databricks.logging.AttributionContextTracing.withAttributionTags$(AttributionContextTracing.scala:76)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:27)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags0(DatabricksSparkUsageLogger.scala:74)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.withAttributionTags(DatabricksSparkUsageLogger.scala:174)
	at com.databricks.spark.util.UsageLogging.$anonfun$withAttributionTags$1(UsageLogger.scala:491)
	at com.databricks.spark.util.UsageLogging$.withAttributionTags(UsageLogger.scala:603)
	at com.databricks.spark.util.UsageLogging$.withAttributionTags(UsageLogger.scala:612)
	at com.databricks.spark.util.UsageLogging.withAttributionTags(UsageLogger.scala:491)
	at com.databricks.spark.util.UsageLogging.withAttributionTags$(UsageLogger.scala:489)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withAttributionTags(SparkExecuteStatementOperation.scala:69)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.$anonfun$withLocalProperties$11(ThriftLocalProperties.scala:195)
	at com.databricks.spark.util.IdentityClaim$.withClaim(IdentityClaim.scala:48)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:190)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:71)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:69)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:397)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:383)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:433)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.sql.catalyst.parser.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'year'. SQLSTATE: 42601 (line 2, pos 53)

== SQL ==
SELECT 
 (TIMESTAMP('2023-01-01') + INTERVAL num_year_to_add year) AS added_date
-----------------------------------------------------^^^
 FROM my_catalog.my_schema.test_dateadd

	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(parsers.scala:301)
	at org.apache.spark.sql.catalyst.parser.AbstractParser.parse(parsers.scala:114)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:137)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(AbstractSqlParser.scala:106)
	at com.databricks.sql.parser.DatabricksSqlParser.$anonfun$parsePlan$1(DatabricksSqlParser.scala:77)
	at com.databricks.sql.parser.DatabricksSqlParser.parse(DatabricksSqlParser.scala:98)
	at com.databricks.sql.parser.DatabricksSqlParser.parsePlan(DatabricksSqlParser.scala:74)
	at com.databricks.sql.QueryRuntimePrediction.$anonfun$getQueryExecutionWithParsedPlan$3(QueryRuntimePrediction.scala:643)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:431)
	at com.databricks.sql.QueryRuntimePrediction.$anonfun$getQueryExecutionWithParsedPlan$2(QueryRuntimePrediction.scala:640)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:143)
	at com.databricks.sql.QueryRuntimePrediction.$anonfun$getQueryExecutionWithParsedPlan$1(QueryRuntimePrediction.scala:640)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at com.databricks.sql.QueryRuntimePrediction.getQueryExecutionWithParsedPlan(QueryRuntimePrediction.scala:637)
	at com.databricks.sql.QueryRuntimePrediction.getRuntimeCategory(QueryRuntimePrediction.scala:457)
	at com.databricks.sql.ClusterLoadMonitor.$anonfun$getRuntimeCategory$3(ClusterLoadMonitor.scala:556)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:45)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)
	at scala.util.Using$.resource(Using.scala:269)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)
	at com.databricks.sql.ClusterLoadMonitor.$anonfun$getRuntimeCategory$2(ClusterLoadMonitor.scala:552)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at org.apache.spark.util.threads.SparkThreadLocalCapturingRunnable.$anonfun$run$1(SparkThreadLocalForwardingThreadPoolExecutor.scala:134)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.IdentityClaim$.withClaim(IdentityClaim.scala:48)
	at org.apache.spark.util.threads.SparkThreadLocalCapturingHelper.$anonfun$runWithCaptured$4(SparkThreadLocalForwardingThreadPoolExecutor.scala:91)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:45)
	at org.apache.spark.util.threads.SparkThreadLocalCapturingHelper.runWithCaptured(SparkThreadLocalForwardingThreadPoolExecutor.scala:90)
	at org.apache.spark.util.threads.SparkThreadLocalCapturingHelper.runWithCaptured$(SparkThreadLocalForwardingThreadPoolExecutor.scala:67)
	at org.apache.spark.util.threads.SparkThreadLocalCapturingRunnable.runWithCaptured(SparkThreadLocalForwardingThreadPoolExecutor.scala:131)
	at org.apache.spark.util.threads.SparkThreadLocalCapturingRunnable.run(SparkThreadLocalForwardingThreadPoolExecutor.scala:134)
	... 3 more
, Query: SELECT 
 (***.

</details>

**Comment by schuemie** [comment]
SqlRender translates from 'OHDSISql' to other languages. OHDSISql is (mostly) a subset of SQL Server SQL, and is loosely documented [here](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate). As you can see `TIMESTAMP()` is not a part of OHDSISql. What you probably want is `CAST('yyyymmdd' AS DATE)`. This translates just fine to all supported dialects:

```sql
SELECT (DATEADD(YEAR, num_year_to_add, CAST('20230101' AS DATE)) AS added_date
FROM my_catalog.my_schema.test_dateadd;
```

**Comment by kzollove** [comment]
Thanks. I'm not sure the TIMESTAMP is the problem here. The following queries all work:

```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, 3,TIMESTAMP('2023-01-01')) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, 3 ,DATE('2023-01-01')) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, 3,CAST('2023-01-01' AS DATE)) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

But these do not:

```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, num_year_to_add,TIMESTAMP('2023-01-01')) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, num_year_to_add,DATE('2023-01-01')) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

```R
renderTranslateQuerySql(connection, sql = "SELECT 
    DATEADD(YEAR, num_year_to_add,CAST('2023-01-01' AS DATE)) AS added_date
    FROM my_catalog.my_schema.test_dateadd
")
```

**Comment by schuemie** [comment]
Seems to work fine for me:

```r
executeSql(conn, "CREATE TABLE scratch.test (x INT);")
executeSql(conn, "INSERT INTO TABLE scratch.test (x) VALUES (1);")
renderTranslateQuerySql(conn, sql = "SELECT 
    DATEADD(YEAR, x, CAST('20230101' AS DATE)) AS added_date
    FROM scratch.test;
")
#  ADDED_DATE
# 1 2024-01-01
```

**Comment by bdeboe** [comment]
<wild guess alert>

Any chance this may have to do with the underscores in the field name used as the second argument to `DATEADD()`? There are some slightly overlapping rewrite rules for this and that underscore seems to be a difference between what works and what doesn't. That, as well as simple rules for the `YY` and `YYYY` date parts and a separate one for a generic date part. 

This is just based on a quick look at the rewrite rules, after having spent some time on them for a different database.

**Comment by kzollove** [comment]
Apologies, my SqlRender had fallen out of date. All of these cases seem to work completely fine.

**Comment by schuemie** [comment]
> All of these cases seem to work completely fine.

Please keep in mind that even though they might work fine on your database platform, not all may work across all platforms. The code I wrote *should* run everywhere.

**Comment by kzollove** [comment]
Thanks for the reminder and the more SqlRender-compliant code
